// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, password_hash)
VALUES ($1, $2)
RETURNING id
`

type CreateAccountParams struct {
	Username     string `json:"username"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, created_at, updated_at
FROM accounts
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID        uuid.UUID        `json:"id"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, created_at, updated_at
FROM accounts
WHERE username = $1
`

type GetAccountByUsernameRow struct {
	ID        uuid.UUID        `json:"id"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoginCredential = `-- name: GetLoginCredential :one
SELECT id, username, password_hash
FROM accounts
WHERE username = $1
`

type GetLoginCredentialRow struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash []byte    `json:"password_hash"`
}

func (q *Queries) GetLoginCredential(ctx context.Context, username string) (GetLoginCredentialRow, error) {
	row := q.db.QueryRow(ctx, getLoginCredential, username)
	var i GetLoginCredentialRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}
