// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (room_id, author_id, content)
VALUES ($1, $2, $3)
`

type CreateMessageParams struct {
	RoomID   uuid.UUID `json:"room_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage, arg.RoomID, arg.AuthorID, arg.Content)
	return err
}

const getMessagesByRoomID = `-- name: GetMessagesByRoomID :many
SELECT
    m.id AS message_id,
    m.room_id,
    m.content,
    m.created_at,
    m.updated_at,
    m.author_id,
    a.username AS author_name
FROM messages AS m
INNER JOIN accounts AS a ON m.author_id = a.id
WHERE m.room_id = $1
ORDER BY m.created_at ASC
`

type GetMessagesByRoomIDRow struct {
	MessageID  uuid.UUID        `json:"message_id"`
	RoomID     uuid.UUID        `json:"room_id"`
	Content    string           `json:"content"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	AuthorID   uuid.UUID        `json:"author_id"`
	AuthorName string           `json:"author_name"`
}

func (q *Queries) GetMessagesByRoomID(ctx context.Context, roomID uuid.UUID) ([]GetMessagesByRoomIDRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByRoomIDRow{}
	for rows.Next() {
		var i GetMessagesByRoomIDRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RoomID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
