// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID        `json:"id"`
	Username     string           `json:"username"`
	PasswordHash []byte           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Message struct {
	ID        uuid.UUID        `json:"id"`
	RoomID    uuid.UUID        `json:"room_id"`
	AuthorID  uuid.UUID        `json:"author_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Room struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedBy uuid.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
