// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error)
	GetAccountByUsername(ctx context.Context, username string) (GetAccountByUsernameRow, error)
	GetLoginCredential(ctx context.Context, username string) (GetLoginCredentialRow, error)
	GetMessagesByRoomID(ctx context.Context, roomID uuid.UUID) ([]GetMessagesByRoomIDRow, error)
	GetRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
